version: "3.7"
services:
  app:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: always
    environment:
      MYSQL_DATABASE: travellist
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: travellist_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - travellist
    ports:
      - 33060:3306

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./docker-compose/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    networks:
      - travellist
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes: 
      - /certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

    
  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    environment:
      - VIRTUAL_HOST=admindenegocios.com
      - LETSENCRYPT_HOST=admindenegocios.com
      - LETSENCRYPT_EMAIL=fran7paco10@gmail.com
    networks:
      - travellist

networks:
  travellist:
    driver: bridge
